name: Fetch latest information
on:
  schedule:
    - cron: "0 */4 * * *" # run once every 4 hours
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Enable Homebrew
        uses: raviqqe/enable-homebrew@v0.1.0

      - run: brew install htmlq

      - name: Checks for updates
        run: |
          page=$(curl -s -k https://www.net-entreprises.fr/declaration/outils-de-controle-dsn-val/)
          url=$(echo $page | htmlq 'strong' --attribute href a | head -1 | sed 's/ *$//g')
          version=$(echo $page | htmlq 'strong' --text | grep "Version 20" | head -1 | sed 's/ *$//g')
          json=$(jq -n --arg version "$version" --arg url "$url" '{version: $version, url: $url}')
          echo $json > data.json

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Apply net-entreprises changes
          branch: main
          file_pattern: data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
