name: Fetch latest information
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew update
      - run: brew install htmlq

      - name: Checks for updates
        run: |
          page=$(curl -s -k https://www.net-entreprises.fr/declaration/outils-de-controle-dsn-val/)
          url=$(echo "$page" | htmlq 'strong' --attribute href a | tail -1 | sed 's/[[:space:]]*$//')
          version=$(echo "$page" | htmlq 'strong' --text | grep "Version 20" | tail -1 | sed 's/[[:space:]]*$//')
          json=$(jq -n --arg version "$version" --arg url "$url" '{version: $version, url: $url}')
          echo $json > data.json

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply net-entreprises changes
          branch: main
          file_pattern: data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
