name: Fetch latest information
on:
  schedule:
    - cron: "0 */4 * * *" # run once every 4 hours
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Fetch net-entreprises
        run: |
          curl -k https://www.net-entreprises.fr/declaration/outils-de-controle-dsn-val/ > page.html

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Apply net-entreprises changes
          branch: main
          file_pattern: page.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
